services:
  app:
    image: robiningelbrecht/strava-statistics:latest
    container_name: statistics-for-strava
    restart: unless-stopped
    volumes:
      - ./config:/var/www/config/app
      - ./build:/var/www/build
      - ./storage/database:/var/www/storage/database
      - ./storage/files:/var/www/storage/files
    environment:
      - TZ=${TZ}
      - STRAVA_CLIENT_ID=${STRAVA_CLIENT_ID}
      - STRAVA_CLIENT_SECRET=${STRAVA_CLIENT_SECRET}
      - STRAVA_REFRESH_TOKEN=${STRAVA_REFRESH_TOKEN}
      - SFS_BASE_URL=${SFS_BASE_URL}
      - SFS_APP_SUBTITLE=${SFS_APP_SUBTITLE}
      - SFS_APP_DESCRIPTION=${SFS_APP_DESCRIPTION}
      - SFS_AI_API_KEY=${SFS_AI_API_KEY}
      - SFS_AI_ENABLED=${SFS_AI_ENABLED}
      - SFS_AI_UI_ENABLED=${SFS_AI_UI_ENABLED}
      - SFS_AI_PROVIDER=${SFS_AI_PROVIDER}
      - SFS_AI_MODEL_NAME=${SFS_AI_MODEL_NAME}
      - SFS_AI_OLLAMA_URL=${SFS_AI_OLLAMA_URL}
      - SFS_PROFILE_PICTURE_URL=${SFS_PROFILE_PICTURE_URL}
      - SFS_ATHLETE_BIRTHDAY=${SFS_ATHLETE_BIRTHDAY}
      - SFS_ATHLETE_MAX_HR_FORMULA=${SFS_ATHLETE_MAX_HR_FORMULA}
      - SFS_ATHLETE_HEART_RATE_ZONES=${SFS_ATHLETE_HEART_RATE_ZONES}
      - SFS_ATHLETE_WEIGHT_HISTORY=${SFS_ATHLETE_WEIGHT_HISTORY}
      - SFS_ATHLETE_FTP_HISTORY=${SFS_ATHLETE_FTP_HISTORY}
      - SFS_APPEARANCE_LOCALE=${SFS_APPEARANCE_LOCALE}
      - SFS_APPEARANCE_UNIT_SYSTEM=${SFS_APPEARANCE_UNIT_SYSTEM}
      - SFS_APPEARANCE_TIME_FORMAT=${SFS_APPEARANCE_TIME_FORMAT}
      - SFS_APPEARANCE_SHORT_DATE_FORMAT=${SFS_APPEARANCE_SHORT_DATE_FORMAT}
      - SFS_APPEARANCE_NORMAL_DATE_FORMAT=${SFS_APPEARANCE_NORMAL_DATE_FORMAT}
      - SFS_APPEARANCE_HEATMAP_POLYLINE_COLOR=${SFS_APPEARANCE_HEATMAP_POLYLINE_COLOR}
      - SFS_APPEARANCE_HEATMAP_TILE_LAYER_URL=${SFS_APPEARANCE_HEATMAP_TILE_LAYER_URL}
      - SFS_APPEARANCE_HEATMAP_ENABLE_GRAYSCALE=${SFS_APPEARANCE_HEATMAP_ENABLE_GRAYSCALE}
      - SFS_APPEARANCE_PHOTOS_HIDE_FOR_SPORT_TYPES=${SFS_APPEARANCE_PHOTOS_HIDE_FOR_SPORT_TYPES}
      - SFS_APPEARANCE_SPORT_TYPES_SORTING_ORDER=${SFS_APPEARANCE_SPORT_TYPES_SORTING_ORDER}
      - SFS_IMPORT_ACTIVITIES_PER_IMPORT=${SFS_IMPORT_ACTIVITIES_PER_IMPORT}
      - SFS_IMPORT_SPORT_TYPES_TO_IMPORT=${SFS_IMPORT_SPORT_TYPES_TO_IMPORT}
      - SFS_IMPORT_ACTIVITY_VISIBILITIES_TO_IMPORT=${SFS_IMPORT_ACTIVITY_VISIBILITIES_TO_IMPORT}
      - SFS_IMPORT_SKIP_ACTIVITIES_BEFORE=${SFS_IMPORT_SKIP_ACTIVITIES_BEFORE}
      - SFS_IMPORT_ACTIVITIES_TO_SKIP=${SFS_IMPORT_ACTIVITIES_TO_SKIP}
      - SFS_IMPORT_OPT_IN_SEGMENT_IMPORT=${SFS_IMPORT_OPT_IN_SEGMENT_IMPORT}
      - SFS_METRICS_EDDINGTON=${SFS_METRICS_EDDINGTON}
      - SFS_ZWIFT_LEVEL=${SFS_ZWIFT_LEVEL}
      - SFS_ZWIFT_RACING_SCORE=${SFS_ZWIFT_RACING_SCORE}
      - ADDITIONAL_ENVS=${ADDITIONAL_ENVS}